### ISSUE TITLE
How to create a container(python 3.6.*) with 2.2.8 expat

### ISSUE THREAD

**Issue by zybjcdl** [libexpat/libexpat#353]
Here is my Docker file, I changed expat to 2.2.8 to fix CVE-2019-15903 security issue:
```
FROM python:3.6.9-alpine
RUN apk add --update python3-dev gcc musl-dev
RUN apk add --update expat=2.2.8
```
It will run with following error:
```
  expat-2.2.7-r0:
    breaks: world[expat=2.2.8]
    satisfies: python3-3.7.3-r0[so:libexpat.so.1]
               .python-rundeps-20190821.002826[so:libexpat.so.1]
```

I also tried with other python version : 3.7.4-alpine, 3.8.0b4-alpine. All these reported such error. How could I upgrade the expat to 2.2.8?
